'use strict'

const yargs = require('yargs')
const exit = require('promise-exit')

const genIndex = require('.').default

const { argv } = yargs
  .option('cwd', {
    default: process.cwd(),
  })
  .option('overwrite', {
    default: false,
  })
  .option('output', {
    default: 'index.mjs',
  })
  .option('dry-run', {
    default: false,
  })
  .option('format', {
    default: 'named-export',
  })
  .option('banner', {
    default:
      '// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.',
  })

exit(genIndex(argv))
